name: Deploy to Microsoft Fabric

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        type: choice
        options: ['dev', 'staging', 'prod']
        default: 'dev'
      deploy_mode:
        description: 'Deployment mode'
        type: choice
        options: ['auto', 'incremental', 'full']
        default: 'auto'
      dry_run:
        description: 'Perform dry run validation only'
        required: false
        default: false
        type: boolean

jobs:
  deploy:
    uses: olepetter-no/fabric-deploy-workflow/.github/workflows/fabric-deploy.yml@main
    with:
      fabric_workspace_id: ${{ vars.FABRIC_WORKSPACE_ID }}
      source_directory: './fabric-artifacts'
      environment: ${{ inputs.environment }}
      deploy_mode: ${{ inputs.deploy_mode }}
      dry_run: ${{ inputs.dry_run }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
