name: Deploy to Development

on:
  workflow_dispatch:
    inputs:
      workspace_id:
        description: 'Microsoft Fabric workspace ID'
        required: true
        type: string
      deploy_mode:
        description: 'Deployment mode'
        type: choice
        options: ['full', 'incremental']
        default: 'full'
      unpublish_orphan_items:
        description: 'Unpublish orphan items from the workspace'
        type: boolean
        default: true
      standardize_default_lakehouse:
        description: 'Standardize default lakehouse references'
        type: boolean
        default: true
      update_deployment_tag:
        description: 'Create/update deployment tags for change tracking'
        type: boolean
        default: true
      verbose:
        description: 'Enable verbose (debug-level) output.'
        required: false
        type: boolean
        default: false

jobs:
  deploy-development:
    permissions:
      contents: write  # Required for pushing git tags
      id-token: write  # Required for Azure authentication
    # 🔒 Pin to a release tag (recommended), or a commit SHA
    uses: olepetter-no/fabric-deploy-workflow/.github/workflows/fabric-deploy.yml@v1.0.0
    with:
      workspace_id: ${{ inputs.workspace_id }}
      source_directory: './fabric-artifacts'   # path in THIS repo
      environment: 'dev'
      deploy_mode: ${{ inputs.deploy_mode }}
      unpublish_orphan_items: ${{ inputs.unpublish_orphan_items }}
      standardize_default_lakehouse: ${{ inputs.standardize_default_lakehouse }}
      update_deployment_tag: ${{ inputs.update_deployment_tag }}
      verbose: ${{ inputs.verbose }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
