name: Deploy to Production

on:
  workflow_dispatch:
    # Only allow manual triggers from main branch
    # Note: GitHub will only show this workflow when viewing main branch

jobs:
  deploy-production:
    # Extra safety: ensure we're on main branch
    if: github.ref == 'refs/heads/main'
    environment: production  # Requires approval in GitHub settings
    uses: olepetter-no/fabric-deploy-workflow/.github/workflows/fabric-deploy.yml@main
    with:
      fabric_workspace_id: ${{ vars.PROD_FABRIC_WORKSPACE_ID }}
      source_directory: './fabric-artifacts'
      environment: 'prod'
      deploy_mode: 'full'
      standardize_lakehouse_refs: true
      fabric_item_types: ''  # Deploy all types
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.PROD_AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.PROD_AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
