name: Deploy to Staging

on:
  push:
    branches: [stage]
    paths:
      - 'fabric/**'              # adjust to match your real artifact dir
  workflow_dispatch:
    inputs:
      deploy_mode:
        description: 'Deployment mode (override default incremental)'
        type: choice
        options: ['incremental', 'full']
        default: 'incremental'
      update_deployment_tag:
        description: 'Create/update deployment tags for change tracking'
        type: boolean
        default: true
      standardize_lakehouse_refs:
        description: 'Standardize lakehouse references'
        type: boolean
        default: true

jobs:
  deploy-staging:
    # Safety: only run when the ref is stage
    if: github.ref == 'refs/heads/stage'
    environment: stage
    uses: olepetter-no/fabric-deploy-workflow/.github/workflows/fabric-deploy.yml@v1.0.0
    with:
      fabric_workspace_id: ${{ vars.STAGE_FABRIC_WORKSPACE_ID }}
      source_directory: './fabric'                             # keep consistent with push paths
      environment: 'stage'
      # Default to incremental on push; allow override when manually dispatched
      deploy_mode: ${{ github.event_name == 'workflow_dispatch' && inputs.deploy_mode || 'incremental' }}
      standardize_lakehouse_refs: ${{ github.event_name == 'workflow_dispatch' && inputs.standardize_lakehouse_refs || true }}
      update_deployment_tag: ${{ github.event_name == 'workflow_dispatch' && inputs.update_deployment_tag || true }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
