name: Incremental Fabric Deployment

on:
  push:
    branches: [main]
    paths: ['fabric-artifacts/**']
  pull_request:
    branches: [main]
    paths: ['fabric-artifacts/**']

jobs:
  # Deploy to dev on every push to main
  deploy-dev:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: olepetter-no/fabric-deploy-workflow/.github/workflows/fabric-deploy.yml@main
    with:
      fabric_workspace_id: ${{ vars.DEV_FABRIC_WORKSPACE_ID }}
      source_directory: './fabric-artifacts'
      environment: 'dev'
      deploy_mode: 'incremental'  # Force incremental for dev
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.DEV_AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.DEV_AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

  # Validate changes on PRs
  validate-pr:
    if: github.event_name == 'pull_request'
    uses: olepetter-no/fabric-deploy-workflow/.github/workflows/fabric-deploy.yml@main
    with:
      fabric_workspace_id: ${{ vars.DEV_FABRIC_WORKSPACE_ID }}
      source_directory: './fabric-artifacts'
      environment: 'dev'
      deploy_mode: 'incremental'
      dry_run: true  # Only validate, don't deploy
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.DEV_AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.DEV_AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}