name: Simple Configuration Example

on:
  workflow_dispatch:
    inputs:
      fabric_workspace_id:
        description: 'Microsoft Fabric workspace ID'
        required: true
        type: string
      source_directory:
        description: 'Directory containing Fabric artifacts'
        type: string
        default: './fabric-artifacts'
      environment:
        description: 'Target environment'
        type: choice
        options: ['dev', 'staging', 'prod']
        default: 'dev'
      deploy_mode:
        description: 'Deployment mode'
        type: choice
        options: ['full', 'incremental']
        default: 'full'
      dry_run:
        description: 'Perform dry run only'
        type: boolean
        default: false
      python_version:
        description: 'Python version to use'
        type: string
        default: '3.12'
      standardize_lakehouse_refs:
        description: 'Standardize lakehouse references'
        type: boolean
        default: false
      fabric_item_types:
        description: 'Fabric items to deploy (comma-separated, e.g., "Notebook,DataPipeline")'
        type: string
        default: ''  # Deploy all types by default

jobs:
  deploy:
    uses: olepetter-no/fabric-deploy-workflow/.github/workflows/fabric-deploy.yml@main
    with:
      fabric_workspace_id: ${{ inputs.fabric_workspace_id }}
      source_directory: ${{ inputs.source_directory }}
      environment: ${{ inputs.environment }}
      deploy_mode: ${{ inputs.deploy_mode }}
      dry_run: ${{ inputs.dry_run }}
      python_version: ${{ inputs.python_version }}
      standardize_lakehouse_refs: ${{ inputs.standardize_lakehouse_refs }}
      fabric_item_types: ${{ inputs.fabric_item_types }}
    secrets:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
